version: "3.9"

services:
  user_api_service:
    build:
      context: ./user_api_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./user_api_service:/app
    environment:
      - PYTHONUNBUFFERED=1

  marketplace_api_service:
    build:
      context: ./marketplace_api_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./marketplace_api_service:/app
    environment:
      - PYTHONUNBUFFERED=1