
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=archdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d archdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  user_api_service:
    build:
      context: ./user_api_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./user_api_service:/app
    environment:
      - PYTHONUNBUFFERED=1


volumes:
  postgres_data: